### ISSUE TITLE
Button Alignment

### ISSUE THREAD

**Issue by Natgho** [saxix/django-admin-extra-buttons#12]
When I add a new button, it is automatically adding horizontally, if the option for alignment of all buttons, it will be useful, like this;
![image](https://user-images.githubusercontent.com/6623948/214772831-7c22fc29-e18f-40fc-8625-22e12b087a6c.png)

**Comment by saxix** [comment]
sadly this is not easy without more invasive changes to the templates. It is easier to implement locally. Let me know if you need help on this

**Comment by senabo** [comment]
@Natgho , I've created a custom mixin with override styles for object-tools block (extra buttons are rendering there)

```python
class CustomExtraButtonsMixin(ExtraButtonsMixin):
    """
    Extra buttons mixin with buttons layout fix.
    """
    class Media:
        css = {
            'all': ('css/admin/extra-buttons/buttons-layout.css',)
        }

``` 
and `buttons-layout.css`:

```css
.object-tools {
    font-size: 0.625rem;
    font-weight: bold;
    /* Disable default styles */
    padding-left: 0;
    float: none;
    position: unset;
    margin-top: 0;

    /* Custom styles to fix layout */
    display: flex;
    flex-wrap: wrap;
    padding-bottom: 16px;
    gap: 16px;
    justify-content: flex-start;
}

@media (max-width: 767px) {
    .object-tools li + li {
        margin-left: 0!important;
    }
}

```
Result:

![Screenshot_20240119_000230](https://github.com/saxix/django-admin-extra-buttons/assets/47538029/dd567e44-aa97-4865-9004-d772e04e9ee6)

and responsive:

![Screenshot_20240119_000421](https://github.com/saxix/django-admin-extra-buttons/assets/47538029/98450440-c0ed-401f-b5dd-292b65901790)
