### ISSUE TITLE
My simple (but not perfect) solution for the broken buttons alignment

### ISSUE THREAD

**Issue by senabo** [saxix/django-admin-extra-buttons#20]
reference to the closed issue #12 

I've created a custom mixin with override styles for object-tools block (extra buttons are rendering there)

```python
class CustomExtraButtonsMixin(ExtraButtonsMixin):
    """
    Extra buttons mixin with buttons layout fix.
    """
    class Media:
        css = {
            'all': ('css/admin/extra-buttons/buttons-layout.css',)
        }

``` 
and `buttons-layout.css`:

```css
.object-tools {
    font-size: 0.625rem;
    font-weight: bold;
    /* Disable default styles */
    padding-left: 0;
    float: none;
    position: unset;
    margin-top: 0;

    /* Custom styles to fix layout */
    display: flex;
    flex-wrap: wrap;
    padding-bottom: 16px;
    gap: 16px;
    justify-content: flex-start;
}

@media (max-width: 767px) {
    .object-tools li + li {
        margin-left: 0!important;
    }
}

```
Result:

![Screenshot_20240119_000230](https://github.com/saxix/django-admin-extra-buttons/assets/47538029/dd567e44-aa97-4865-9004-d772e04e9ee6)

and responsive:

![Screenshot_20240119_000421](https://github.com/saxix/django-admin-extra-buttons/assets/47538029/98450440-c0ed-401f-b5dd-292b65901790)

_Originally posted by @senabo in https://github.com/saxix/django-admin-extra-buttons/issues/12#issuecomment-1899297578_
